import { Report } from "@shared/api";

/**
 * Initial reports for seeding the database
 */
export const demoReports: Omit<Report, "id">[] = [
  {
    clientId: "client-1",
    clientName: "ABC Enterprises Pvt Ltd",
    financialYear: "2023-24",
    reportType: "Financial Statements",
    status: "final",
    preparedBy: "admin-1",
    preparedByName: "Admin User",
    generatedOn: new Date("2024-03-15").toISOString(),
    data: {
      revenue: 5000000,
      expenses: 3500000,
      profit: 1500000,
      assets: 10000000,
      liabilities: 4000000,
    },
    exportLogs: [],
  },
  {
    clientId: "client-2",
    clientName: "XYZ Solutions Ltd",
    financialYear: "2023-24",
    reportType: "GST Summary",
    status: "final",
    preparedBy: "admin-1",
    preparedByName: "Admin User",
    generatedOn: new Date("2024-03-20").toISOString(),
    data: {
      totalSales: 8000000,
      totalPurchases: 5000000,
      outputGST: 1440000,
      inputGST: 900000,
      netGST: 540000,
    },
    exportLogs: [],
  },
  {
    clientId: "client-1",
    clientName: "ABC Enterprises Pvt Ltd",
    financialYear: "2023-24",
    reportType: "Income Tax Computation",
    status: "draft",
    preparedBy: "admin-1",
    preparedByName: "Admin User",
    generatedOn: new Date("2024-03-25").toISOString(),
    data: {
      grossIncome: 5000000,
      deductions: 500000,
      taxableIncome: 4500000,
      taxAmount: 1350000,
    },
    exportLogs: [],
  },
  {
    clientId: "client-3",
    clientName: "PQR Industries",
    financialYear: "2024-25",
    reportType: "Tax Audit Summary",
    status: "final",
    preparedBy: "admin-1",
    preparedByName: "Admin User",
    generatedOn: new Date("2024-09-30").toISOString(),
    data: {
      turnover: 15000000,
      taxableProfit: 3000000,
      taxPaid: 900000,
      auditObservations: ["All records maintained properly"],
    },
    exportLogs: [],
  },
  {
    clientId: "client-2",
    clientName: "XYZ Solutions Ltd",
    financialYear: "2024-25",
    reportType: "ROC Filing Summary",
    status: "filed",
    preparedBy: "admin-1",
    preparedByName: "Admin User",
    generatedOn: new Date("2024-10-15").toISOString(),
    data: {
      filingType: "Annual Return",
      dueDate: "2024-10-30",
      status: "completed",
      documents: ["Balance Sheet", "Profit & Loss Statement", "Director Report"],
    },
    exportLogs: [],
  },
];
